services:
    postgres:
        build:
            context: .
            args:
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_DB: ${POSTGRES_DB}
                POSTGRES_PORT: ${POSTGRES_PORT}
        container_name: postgres_dev
        restart: always
        env_file:
            - ../../env/.env.dev
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
